MODULE MOD_INTERFACES
  USE MOD_READWRITE
  USE MOD_PROCEDURES_SBR
  USE MOD_PROCEDURES_FCT
  implicit none

  INTERFACE PRINTMAT
    MODULE PROCEDURE PRINTMAT_R,PRINTMAT_I,PRINTMAT_C
  END INTERFACE 

  INTERFACE PRINTVEC
    MODULE PROCEDURE PRINTVEC_R,PRINTVEC_I,PRINTVEC_C
  END INTERFACE 

  INTERFACE FCT_RMSD
    MODULE PROCEDURE FCT_RMSD_VEC,FCT_RMSD_MAT
  END INTERFACE FCT_RMSD

  INTERFACE SBR_RMSD
    MODULE PROCEDURE SBR_RMSD_VEC,SBR_RMSD_MAT
  END INTERFACE SBR_RMSD

  INTERFACE FCT_COM
    MODULE PROCEDURE FCT_COM_VEC,FCT_COM_MAT
  END INTERFACE FCT_COM

  INTERFACE SBR_COM
    MODULE PROCEDURE SBR_COM_VEC,SBR_COM_MAT
  END INTERFACE SBR_COM

END MODULE MOD_INTERFACES